airbnb_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gw99174
      user: SFLEARNING
      role: ACCOUNTADMIN
      warehouse: ADMIN_WH
      database: AIRBNB
      schema: DEV
      threads: 8
    QA:
      type: snowflake
      account: gw99174
      user: SFLEARNING
      role: ACCOUNTADMIN
      warehouse: ADMIN_WH
      database: AIRBNB
      schema: quality_assurance
      threads: 8
    PROD:
      type: snowflake
      account: gw99174
      user: SFLEARNING
      role: ACCOUNTADMIN
      warehouse: ADMIN_WH
      database: AIRBNB
      schema: production
      threads: 8
